#!/usr/bin/env python3
"""Generate openapi.json and the C++ resources embedded in Simutrans."""

import json
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
SPEC_DIR = ROOT / "documentation" / "rest-api"
HEADER = ROOT / "network" / "rest_api_spec_generated.h"


def raw_literal(name: str, content: str) -> str:
	delimiter = "SIM_OPENAPI"
	if f"){delimiter}\"" in content:
		raise ValueError(f"raw-string delimiter occurs in {name}")
	return (
		f"static const char {name}[] = R\"{delimiter}("
		f"{content}){delimiter}\";\n"
	)


yaml_path = SPEC_DIR / "openapi.yaml"
yaml_text = yaml_path.read_text(encoding="utf-8")
document = yaml.safe_load(yaml_text)
json_text = json.dumps(document, ensure_ascii=False, indent=2) + "\n"
(SPEC_DIR / "openapi.json").write_text(json_text, encoding="utf-8")

header_text = """/* Generated by documentation/rest-api/generate_embedded_spec.py. */
#ifndef NETWORK_REST_API_SPEC_GENERATED_H
#define NETWORK_REST_API_SPEC_GENERATED_H

"""
header_text += raw_literal("REST_API_OPENAPI_YAML", yaml_text)
header_text += "\n"
header_text += raw_literal("REST_API_OPENAPI_JSON", json_text)
header_text += "\n#endif // NETWORK_REST_API_SPEC_GENERATED_H\n"
HEADER.write_text(header_text, encoding="utf-8")
